name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core SDK
  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Publish .NET Core Project
      run: dotnet publish -c Release -o release --nologo
    - name: Change base-tag in index.html from / to GitHubPagesDemo
      run: sed -i 's/<base href="\/" \/>/<base href="\/GitHubPagesDemo\/" \/>/g' release/wwwroot/index.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Commit wwwroot to GitHub Pages
      uses: Asriel159/GitHubPagesDemo/github-pages-deploy-action@4.4.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
